// Source: user's “Liste d'achats matériaux (reste à acheter) - prix fixes”
// Prices are stored in cents (integer) to avoid floating point issues.

window.TRAVAUX_ITEMS = [
  { id: "prot-cons", lot: 0, article: "Protections et consommables", specification: "Bâches, cartons de protection, scotch", qty: 1, unit: "lot", pu_cents: 20000, budget_total_cents: 20000 },
  { id: "evac-dechets", lot: 0, article: "Evacuation / déchets", specification: "Sacs gravats, big-bags, déchetterie", qty: 1, unit: "lot", pu_cents: 15000, budget_total_cents: 15000 },
  { id: "epi-disques", lot: 0, article: "EPI + disques / lames", specification: "Gants, masques, disques, lames, petits outillages", qty: 1, unit: "lot", pu_cents: 18000, budget_total_cents: 18000 },

  { id: "ba13", lot: 1, article: "BA13", specification: "Plaques 2500x1200 (reprises + coffrages)", qty: 10, unit: "plaque", pu_cents: 900, budget_total_cents: 9000 },
  { id: "ossature-placo", lot: 1, article: "Ossature placo", specification: "Rails/montants (R48) + suspentes/angles", qty: 1, unit: "lot", pu_cents: 12000, budget_total_cents: 12000 },
  { id: "bandes-enduits", lot: 1, article: "Bandes + enduits joints", specification: "Bandes papier + enduit + grille", qty: 1, unit: "lot", pu_cents: 15000, budget_total_cents: 15000 },
  { id: "acrylique-visserie", lot: 1, article: "Acrylique / visserie", specification: "Joints, cornières, vis, chevilles", qty: 1, unit: "lot", pu_cents: 7000, budget_total_cents: 7000 },

  { id: "tableau-protections", lot: 2, article: "Tableau + protections", specification: "Coffret 2 rangées + DDR + disjoncteurs", qty: 1, unit: "lot", pu_cents: 45000, budget_total_cents: 45000 },
  { id: "cables", lot: 2, article: "Câbles", specification: "3G2.5/3G1.5/fil de terre (reprise circuits)", qty: 1, unit: "lot", pu_cents: 45000, budget_total_cents: 45000 },
  { id: "icta", lot: 2, article: "Gaines ICTA + accessoires", specification: "Gaines, colliers, goulottes ponctuelles", qty: 1, unit: "lot", pu_cents: 16000, budget_total_cents: 16000 },
  { id: "boites-dcl", lot: 2, article: "Boîtes + DCL", specification: "Boîtes encastrement + boîtes dérivation + DCL", qty: 1, unit: "lot", pu_cents: 11000, budget_total_cents: 11000 },
  { id: "appareillage", lot: 2, article: "Appareillage", specification: "40 pièces (prises + interrupteurs) entrée de gamme", qty: 1, unit: "lot", pu_cents: 24000, budget_total_cents: 24000 },
  { id: "wago", lot: 2, article: "Wago + divers", specification: "Wago, vis, accessoires raccordement", qty: 1, unit: "lot", pu_cents: 14000, budget_total_cents: 14000 },

  { id: "plomb-arrivees", lot: 3, article: "Plomberie (arrivées)", specification: "PER/multicouche + raccords + vannes", qty: 1, unit: "lot", pu_cents: 45000, budget_total_cents: 45000 },
  { id: "plomb-evac", lot: 3, article: "Plomberie (évacuations)", specification: "PVC + coudes + colliers + colle", qty: 1, unit: "lot", pu_cents: 18000, budget_total_cents: 18000 },

  { id: "sanibroyeur", lot: 4, article: "Sanibroyeur robuste", specification: "SFA Sanibest Pro (ou équivalent même gamme)", qty: 1, unit: "u", pu_cents: 99000, budget_total_cents: 99000 },
  { id: "cuvette-wc", lot: 4, article: "Cuvette WC", specification: "WC à poser + abattant", qty: 1, unit: "u", pu_cents: 19000, budget_total_cents: 19000 },
  { id: "kit-clapet", lot: 4, article: "Kit raccord / clapet", specification: "Clapet anti-retour + adaptateurs", qty: 1, unit: "lot", pu_cents: 8500, budget_total_cents: 8500 },
  { id: "tube-refoulement", lot: 4, article: "Tube refoulement", specification: "PVC pression 32 mm", qty: 15, unit: "m", pu_cents: 400, budget_total_cents: 6000 },
  { id: "raccords-refoulement", lot: 4, article: "Raccords refoulement", specification: "Coudes/manchons/colliers", qty: 1, unit: "lot", pu_cents: 6500, budget_total_cents: 6500 },
  { id: "alim-eau-wc", lot: 4, article: "Alim eau WC", specification: "Robinet arrêt + flexibles", qty: 1, unit: "lot", pu_cents: 3500, budget_total_cents: 3500 },
  { id: "extracteur", lot: 4, article: "Extracteur", specification: "Extracteur 100 mm", qty: 1, unit: "u", pu_cents: 9000, budget_total_cents: 9000 },
  { id: "gaine-grille", lot: 4, article: "Gaine + grille", specification: "Gaine + grille sortie", qty: 1, unit: "lot", pu_cents: 2500, budget_total_cents: 2500 },
  { id: "coffrage-demontable", lot: 4, article: "Coffrage démontable", specification: "Bois/BA13/vis pour coffrage accès maintenance", qty: 1, unit: "lot", pu_cents: 14000, budget_total_cents: 14000 },

  { id: "receveur", lot: 5, article: "Receveur douche", specification: "120x80 extra-plat", qty: 1, unit: "u", pu_cents: 24000, budget_total_cents: 24000 },
  { id: "bonde", lot: 5, article: "Bonde douche", specification: "Siphon/bonde + raccord", qty: 1, unit: "u", pu_cents: 4500, budget_total_cents: 4500 },
  { id: "colonne", lot: 5, article: "Colonne douche", specification: "Thermostatique entrée de gamme", qty: 1, unit: "u", pu_cents: 19000, budget_total_cents: 19000 },
  { id: "paroi", lot: 5, article: "Paroi douche", specification: "Paroi 120 cm", qty: 1, unit: "u", pu_cents: 28000, budget_total_cents: 28000 },
  { id: "spec", lot: 5, article: "Kit étanchéité SPEC", specification: "(douche) + bandes angles", qty: 1, unit: "lot", pu_cents: 16000, budget_total_cents: 16000 },
  { id: "meuble-vasque", lot: 5, article: "Meuble vasque", specification: "80 cm", qty: 1, unit: "u", pu_cents: 27000, budget_total_cents: 27000 },
  { id: "mitigeur-lavabo", lot: 5, article: "Mitigeur lavabo", specification: "Entrée de gamme", qty: 1, unit: "u", pu_cents: 7000, budget_total_cents: 7000 },
  { id: "miroir", lot: 5, article: "Miroir / éclairage", specification: "Miroir simple", qty: 1, unit: "u", pu_cents: 6000, budget_total_cents: 6000 },
  { id: "mitigeur-baignoire", lot: 5, article: "Mitigeur baignoire", specification: "Remplacement (économique)", qty: 1, unit: "u", pu_cents: 14000, budget_total_cents: 14000 },
  { id: "divers-plomb-sdb", lot: 5, article: "Divers plomberie SDB", specification: "Flexibles, siphon, robinets", qty: 1, unit: "lot", pu_cents: 12000, budget_total_cents: 12000 },

  { id: "meubles-cuisine", lot: 6, article: "Meubles cuisine", specification: "Kit cuisine env. 3 m linéaire (bas + hauts)", qty: 1, unit: "lot", pu_cents: 125000, budget_total_cents: 125000 },
  { id: "plan-travail", lot: 6, article: "Plan de travail", specification: "Stratifié 3 m", qty: 1, unit: "u", pu_cents: 18000, budget_total_cents: 18000 },
  { id: "evier", lot: 6, article: "Évier", specification: "Inox 1 bac", qty: 1, unit: "u", pu_cents: 12000, budget_total_cents: 12000 },
  { id: "mitigeur-cuisine", lot: 6, article: "Mitigeur cuisine", specification: "Entrée de gamme", qty: 1, unit: "u", pu_cents: 8500, budget_total_cents: 8500 },
  { id: "raccords-vidage", lot: 6, article: "Raccords / vidage", specification: "Siphon + kit raccord", qty: 1, unit: "lot", pu_cents: 4500, budget_total_cents: 4500 },
  { id: "credence", lot: 6, article: "Crédence", specification: "Peinture lessivable / primaire", qty: 1, unit: "lot", pu_cents: 3500, budget_total_cents: 3500 },
  { id: "quincaillerie-cuisine", lot: 6, article: "Quincaillerie", specification: "Rails fixation, vis, chevilles", qty: 1, unit: "lot", pu_cents: 6000, budget_total_cents: 6000 },

  { id: "sol-lvt", lot: 7, article: "Sol clipsable (LVT/SPC)", specification: "88 m² (80 m² + 10% chutes)", qty: 88, unit: "m²", pu_cents: 1500, budget_total_cents: 132000 },
  { id: "sous-couche", lot: 7, article: "Sous-couche", specification: "Sous-couche compatible LVT", qty: 88, unit: "m²", pu_cents: 220, budget_total_cents: 19360 },
  { id: "plinthes", lot: 7, article: "Plinthes", specification: "Plinthes MDF", qty: 70, unit: "m", pu_cents: 350, budget_total_cents: 24500 },
  { id: "profiles-seuils", lot: 7, article: "Profilés / seuils", specification: "8 pièces", qty: 8, unit: "u", pu_cents: 1500, budget_total_cents: 12000 },
  { id: "ragreage", lot: 7, article: "Ragréage", specification: "4 sacs", qty: 4, unit: "sac", pu_cents: 2800, budget_total_cents: 11200 },
  { id: "primaire-5l", lot: 7, article: "Primaire", specification: "5 L", qty: 1, unit: "u", pu_cents: 3000, budget_total_cents: 3000 },
  { id: "carrelage", lot: 7, article: "Carrelage / faïence", specification: "23 m² (douche + sol SDB) + 10% chutes", qty: 23, unit: "m²", pu_cents: 1600, budget_total_cents: 36800 },
  { id: "colle-carrelage", lot: 7, article: "Colle carrelage", specification: "5 sacs", qty: 5, unit: "sac", pu_cents: 2000, budget_total_cents: 10000 },
  { id: "joints-carrelage", lot: 7, article: "Joints carrelage", specification: "4 sacs", qty: 4, unit: "sac", pu_cents: 1200, budget_total_cents: 4800 },
  { id: "silicone", lot: 7, article: "Silicone", specification: "6 tubes", qty: 6, unit: "tube", pu_cents: 900, budget_total_cents: 5400 },
  { id: "cales-croisillons", lot: 7, article: "Cales / croisillons", specification: "Kit", qty: 1, unit: "lot", pu_cents: 2500, budget_total_cents: 2500 },

  { id: "enduits", lot: 8, article: "Enduits", specification: "Rebouchage / lissage", qty: 1, unit: "lot", pu_cents: 8000, budget_total_cents: 8000 },
  { id: "abrasifs", lot: 8, article: "Abrasifs", specification: "Papier / disques", qty: 1, unit: "lot", pu_cents: 6000, budget_total_cents: 6000 },
  { id: "sous-couche-15l", lot: 8, article: "Sous-couche", specification: "15 L", qty: 1, unit: "lot", pu_cents: 9000, budget_total_cents: 9000 },
  { id: "peinture-plafond", lot: 8, article: "Peinture plafond", specification: "20 L", qty: 1, unit: "lot", pu_cents: 14000, budget_total_cents: 14000 },
  { id: "peinture-murs", lot: 8, article: "Peinture murs", specification: "50 L", qty: 1, unit: "lot", pu_cents: 35000, budget_total_cents: 35000 },
  { id: "peinture-boiseries", lot: 8, article: "Peinture boiseries", specification: "2,5 L", qty: 1, unit: "lot", pu_cents: 4000, budget_total_cents: 4000 },
  { id: "rouleaux-bacs", lot: 8, article: "Rouleaux / bacs", specification: "Consommables", qty: 1, unit: "lot", pu_cents: 8000, budget_total_cents: 8000 },

  { id: "osb", lot: 9, article: "OSB 18 mm", specification: "13 plaques", qty: 13, unit: "plaque", pu_cents: 2200, budget_total_cents: 28600 },
  { id: "bois-renforts", lot: 9, article: "Bois renforts", specification: "Lambourdes / chevrons", qty: 1, unit: "lot", pu_cents: 45000, budget_total_cents: 45000 },
  { id: "visserie-sabots", lot: 9, article: "Visserie / sabots", specification: "Fixations plancher", qty: 1, unit: "lot", pu_cents: 12000, budget_total_cents: 12000 },
  { id: "isolation", lot: 9, article: "Isolation", specification: "50 m² laine 200 mm", qty: 50, unit: "m²", pu_cents: 850, budget_total_cents: 42500 },
  { id: "pare-vapeur", lot: 9, article: "Pare-vapeur", specification: "Films + adhésifs", qty: 1, unit: "lot", pu_cents: 17000, budget_total_cents: 17000 },
  { id: "ossature-combles", lot: 9, article: "Ossature combles", specification: "Rails / montants", qty: 1, unit: "lot", pu_cents: 32000, budget_total_cents: 32000 },
  { id: "ba13-combles", lot: 9, article: "BA13 combles", specification: "25 plaques", qty: 25, unit: "plaque", pu_cents: 900, budget_total_cents: 22500 },
  { id: "bandes-combles", lot: 9, article: "Bandes / enduits combles", specification: "Joints", qty: 1, unit: "lot", pu_cents: 18000, budget_total_cents: 18000 },
  { id: "velux", lot: 9, article: "Velux", specification: "GGL 78x98", qty: 1, unit: "u", pu_cents: 54000, budget_total_cents: 54000 },
  { id: "raccord-velux", lot: 9, article: "Raccord étanchéité", specification: "Kit raccord Velux", qty: 1, unit: "u", pu_cents: 14000, budget_total_cents: 14000 },
  { id: "habillage-velux", lot: 9, article: "Habillage intérieur", specification: "Kit", qty: 1, unit: "u", pu_cents: 11000, budget_total_cents: 11000 },
  { id: "store-velux", lot: 9, article: "Store occultant", specification: "Intérieur", qty: 1, unit: "u", pu_cents: 9500, budget_total_cents: 9500 },
  { id: "elec-combles", lot: 9, article: "Électricité combles", specification: "Câbles + 2 prises + luminaire", qty: 1, unit: "lot", pu_cents: 16000, budget_total_cents: 16000 },

  { id: "escalier", lot: 10, article: "Escalier", specification: "Escalier droit sapin", qty: 1, unit: "u", pu_cents: 85000, budget_total_cents: 85000 },
  { id: "garde-corps", lot: 10, article: "Garde-corps", specification: "Main courante + garde-corps", qty: 1, unit: "lot", pu_cents: 35000, budget_total_cents: 35000 },
  { id: "renfort-tremie", lot: 10, article: "Renfort trémie", specification: "Bois + quincaillerie", qty: 1, unit: "lot", pu_cents: 32000, budget_total_cents: 32000 },
  { id: "habillage-tremie", lot: 10, article: "Habillage trémie", specification: "Placo + ossature", qty: 1, unit: "lot", pu_cents: 22000, budget_total_cents: 22000 },

  { id: "bisplit", lot: 11, article: "Bi-split R32", specification: "Kit 3,5 kW + 2,6 kW (entrée de gamme)", qty: 1, unit: "lot", pu_cents: 125000, budget_total_cents: 125000 },
  { id: "liaisons-frigo", lot: 11, article: "Liaisons frigorifiques", specification: "2 x 10 m", qty: 20, unit: "m", pu_cents: 1200, budget_total_cents: 24000 },
  { id: "goulottes", lot: 11, article: "Goulottes", specification: "Habillage lignes", qty: 1, unit: "lot", pu_cents: 11000, budget_total_cents: 11000 },
  { id: "support-ext", lot: 11, article: "Support extérieur", specification: "Support + silentblocs", qty: 1, unit: "lot", pu_cents: 12000, budget_total_cents: 12000 },
  { id: "pompe-condensats", lot: 11, article: "Pompe condensats", specification: "Mini-pompe (combles)", qty: 1, unit: "u", pu_cents: 13500, budget_total_cents: 13500 },
  { id: "evac-condensats", lot: 11, article: "Évac condensats", specification: "Tuyaux + accessoires", qty: 1, unit: "lot", pu_cents: 4000, budget_total_cents: 4000 },
  { id: "alim-clim", lot: 11, article: "Alimentation clim", specification: "Sectionneur + câble", qty: 1, unit: "lot", pu_cents: 8500, budget_total_cents: 8500 },

  { id: "volets", lot: 12, article: "Volet roulant électrique PVC", specification: "(standard) - fenêtres", qty: 2, unit: "u", pu_cents: 32000, budget_total_cents: 64000 },
  { id: "commandes-volets", lot: 12, article: "Commandes / câblage", specification: "Boîtes + commandes + divers", qty: 1, unit: "lot", pu_cents: 12000, budget_total_cents: 12000 },

  { id: "imprevus", lot: 13, article: "Imprévus + consommables", specification: "Visserie, colles, petites reprises, pertes, divers", qty: 1, unit: "lot", pu_cents: 251376, budget_total_cents: 251376 },
];

